name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  go_router: ^13.2.0
  http: ^1.2.0
  shared_preferences: ^2.2.1
  sqflite: ^2.3.0
  get_it: ^7.6.7
  dio: ^5.4.0
  retrofit: ^4.0.3
  provider: ^6.0.0
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  loading_indicator: ^3.1.1
  mockito: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.8
  custom_lint: ^0.5.8
  riverpod_lint: ^2.3.7
  retrofit_generator: ^8.0.6
  freezed: ^2.4.6

flutter:
  uses-material-design: true
